spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: EMPLOYEE
              uri: lb://EMPLOYEE
              predicates:
                - Path=/employees/**
              filters:
                - AuthFilter
#                - name: CircuitBreaker
#                  args:
#                    name: EMPLOYEE-SERVICE
#                    fallbackUri: forward:/employeeServiceFallback

            - id: ADDRESS
              uri: lb://ADDRESS
              predicates:
                - Path=/address/**
              filters:
                - AuthFilter
#                - name: CircuitBreaker
#                  args:
#                    name: ADDRESS-SERVICE
#                    fallbackUri: forward:/addressServiceFallback

            - id: AUTH
              uri: lb://AUTH
              predicates:
                - Path=/auth/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#  instance:
#    prefer-ip-address: true